---

- name: clone snapraid-runner
  git:
    repo: "{{ snapraid_run_repo }}"
    dest: /opt/snapraid-runner

- name: install snapraid-runner configuration file
  template:
    src: "{{ snapraid_run_conf_template }}"
    dest: "{{ snapraid_run_conf }}"
    owner: root
    group: root
    mode: 0775  

- name: setup cron job snapraid-runner
  cron:
    user: "root"
    job: "{{ item.job }}"
    name: "{{ item.name }}"
    weekday: "{{ item.weekday | default ('*') }}"
    minute: "{{ item.minute | default ('00')}}"
    hour: "{{ item.hour | default ('00') }}"
    dom: "{{ item.dom|default('*') }}"
  with_items:
    - "{{ snapraid_cron_jobs }}"
    